// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNmg_UA8Lx7WddbngXmDANDR1Wy-Z7U3M',
    appId: '1:621546694766:android:066bfcd1787ab417ae9e7f',
    messagingSenderId: '621546694766',
    projectId: 'books-information-4500f',
    databaseURL: 'https://books-information-4500f-default-rtdb.firebaseio.com',
    storageBucket: 'books-information-4500f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2ha0q98Sre2BQu9JqsU0mShsNTAD4Z48',
    appId: '1:621546694766:ios:f0ed1df0c02229c8ae9e7f',
    messagingSenderId: '621546694766',
    projectId: 'books-information-4500f',
    databaseURL: 'https://books-information-4500f-default-rtdb.firebaseio.com',
    storageBucket: 'books-information-4500f.appspot.com',
    iosBundleId: 'com.example.remoteConfigExample',
  );
}
